'use strict';
(() => {
  const state={meta:null,employees:[],editing:null};const $=s=>document.querySelector(s),toast=$('#toast'),dialog=$('#grade-dialog');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200)};
  async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  function render(){const m=state.meta;$('#grade-list').innerHTML=m.grades.map(g=>`<article class="grade-item"><div class="grade-level" style="color:${g.color}">${g.level}</div><div><strong>${g.name}</strong><p>${g.departmentName||'Tous les départements'} · ${g.permissions.length} permission(s)</p></div><div class="grade-actions"><button class="secondary-action edit-grade" data-id="${g.id}">Modifier</button><button class="danger-action delete-grade" data-id="${g.id}">Supprimer</button></div></article>`).join('')||'<p>Aucun grade.</p>';document.querySelectorAll('.edit-grade').forEach(b=>b.onclick=()=>openGrade(Number(b.dataset.id)));document.querySelectorAll('.delete-grade').forEach(b=>b.onclick=async()=>{if(!confirm('Supprimer ce grade ?'))return;const d=await api(`/api/admin-center/grades/${b.dataset.id}`,{method:'DELETE'});show(d.message);load()})}
  function openGrade(id=null){state.editing=id;const g=id?state.meta.grades.find(x=>x.id===id):null;$('#grade-dialog-title').textContent=g?'Modifier le grade':'Nouveau grade';$('#grade-id').value=g?.id||'';$('#grade-name').value=g?.name||'';$('#grade-level').value=g?.level||0;$('#grade-color').value=g?.color||'#3aa9ff';$('#grade-department').value=g?.departmentId||'';$('#grade-description').value=g?.description||'';$('#grade-active').checked=g?g.active:true;document.querySelectorAll('#grade-permissions input').forEach(x=>x.checked=g?.permissions.includes(x.value)||false);dialog.showModal()}
  async function load(){const [meta,employees]=await Promise.all([api('/api/admin-center/meta'),api('/api/employees')]);state.meta=meta;state.employees=employees.employees;$('#grade-department').innerHTML='<option value="">Tous</option>'+meta.departments.map(d=>`<option value="${d.id}">${d.name}</option>`).join('');$('#grade-permissions').innerHTML='<legend>Permissions héritées</legend>'+meta.permissions.map(p=>`<label class="check-row"><input type="checkbox" value="${p.key}">${p.label}</label>`).join('');$('#rights-user').innerHTML=state.employees.map(u=>`<option value="${u.id}">${u.username} — ${u.matricule}</option>`).join('');render()}
  $('#new-grade').onclick=()=>openGrade();$('#cancel-grade').onclick=()=>dialog.close();$('#grade-form').onsubmit=async e=>{e.preventDefault();const body={name:$('#grade-name').value.trim(),level:Number($('#grade-level').value),color:$('#grade-color').value,departmentId:$('#grade-department').value?Number($('#grade-department').value):null,description:$('#grade-description').value.trim(),active:$('#grade-active').checked,permissions:[...document.querySelectorAll('#grade-permissions input:checked')].map(x=>x.value)};const url=state.editing?`/api/admin-center/grades/${state.editing}`:'/api/admin-center/grades';const d=await api(url,{method:state.editing?'PUT':'POST',body:JSON.stringify(body)});dialog.close();show(d.message);load()};$('#load-rights').onclick=async()=>{const d=await api(`/api/admin-center/users/${$('#rights-user').value}/effective-rights`);$('#rights-result').innerHTML=`<article class="rights-group"><strong>Permissions effectives (${d.effectivePermissions.length})</strong><div>${d.effectivePermissions.map(x=>`<code>${x}</code>`).join('')}</div></article><article class="rights-group"><strong>Grades</strong><p>${d.grades.map(x=>`${x.name} (niveau ${x.level})`).join(', ')||'Aucun'}</p></article>`};load().catch(e=>show(e.message));
})();