'use strict';
(() => {
  const state={departments:[],canManage:false};
  const $=s=>document.querySelector(s), dialog=$('#announcement-dialog'), toast=$('#toast');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200)};
  async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  function fmt(v){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v.endsWith?.('Z')?v:v+'Z'))}
  async function load(){const d=await api('/api/announcements');$('#announcement-list').innerHTML=d.announcements.map(a=>`<article class="announcement-card" data-priority="${a.priority}">${a.pinned?'<span>📌 Épinglée</span>':''}<h2>${a.title}</h2><p class="announcement-meta">${a.authorName} — ${a.authorGrade} · ${fmt(a.publishAt||a.createdAt)}</p>${a.imageUrl?`<img src="${a.imageUrl}" alt="">`:''}<p>${a.content}</p>${state.canManage?`<button class="archive-announcement secondary-action" data-id="${a.id}">Archiver</button>`:''}</article>`).join('');$('#announcement-empty').hidden=d.announcements.length>0;document.querySelectorAll('.archive-announcement').forEach(b=>b.onclick=async()=>{await api(`/api/announcements/${b.dataset.id}/archive`,{method:'POST'});show('Annonce archivée.');load()})}
  async function init(){const m=await api('/api/announcements/meta');state.departments=m.departments;state.canManage=m.canManage;$('#new-announcement').hidden=!state.canManage;$('#announcement-departments').innerHTML='<legend>Départements autorisés</legend>'+state.departments.map(d=>`<label class="checkbox-row"><input type="checkbox" value="${d}">${d}</label>`).join('');await load()}
  $('#new-announcement').onclick=()=>dialog.showModal();$('#close-announcement').onclick=()=>dialog.close();$('#announcement-global').onchange=()=>{$('#announcement-departments').hidden=$('#announcement-global').checked};
  $('#announcement-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/announcements',{method:'POST',body:JSON.stringify({title:$('#announcement-title').value.trim(),content:$('#announcement-content').value.trim(),priority:$('#announcement-priority').value,imageUrl:$('#announcement-image').value.trim(),publishAt:$('#announcement-publish-at').value?new Date($('#announcement-publish-at').value).toISOString():null,globalVisible:$('#announcement-global').checked,pinned:$('#announcement-pinned').checked,departments:[...document.querySelectorAll('#announcement-departments input:checked')].map(i=>i.value)})});dialog.close();e.target.reset();show('Annonce enregistrée.');load()}catch(err){$('#announcement-message').textContent=err.message}};
  init().catch(e=>show(e.message));
})();
