'use strict';
(() => {
  const $=s=>document.querySelector(s),toast=$('#toast');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2300)};
  async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  async function load(){const d=await api('/api/maintenance');const s=d.state;$(`input[name="mode"][value="${s.mode}"]`).checked=true;$('#maintenance-message').value=s.message||'';const alert=document.querySelector(`input[name="alert-code"][value="${s.alertCode||'green'}"]`);if(alert)alert.checked=true;$('#return-unknown').checked=s.returnUnknown;$('#return-at').disabled=s.returnUnknown;$('#return-at').value=s.returnAt?new Date(s.returnAt).toISOString().slice(0,16):'';$('#maintenance-badge').textContent=s.label;$('#allowed-departments').innerHTML=d.departments.filter(x=>x.active).map(dep=>`<label><input type="checkbox" value="${dep.name}" ${s.allowedDepartments.includes(dep.name)?'checked':''}><span>${dep.icon||'🏢'} ${dep.name}</span></label>`).join('')}
  $('#return-unknown').onchange=()=>{$('#return-at').disabled=$('#return-unknown').checked};
  $('#maintenance-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/maintenance',{method:'PUT',body:JSON.stringify({mode:document.querySelector('input[name="mode"]:checked')?.value,alertCode:document.querySelector('input[name="alert-code"]:checked')?.value||'green',message:$('#maintenance-message').value.trim(),returnUnknown:$('#return-unknown').checked,returnAt:$('#return-at').value?new Date($('#return-at').value).toISOString():null,allowedDepartments:[...document.querySelectorAll('#allowed-departments input:checked')].map(x=>x.value)})});show(d.message);load()}catch(err){show(err.message)}};
  load().catch(e=>show(e.message));
})();