'use strict';
(() => {
  const state={conversations:[],selectedId:null,currentUser:null};const $=s=>document.querySelector(s),toast=$('#toast'),dialog=$('#conversation-dialog');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200)};
  async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  function renderConversations(){const q=$('#conversation-search').value.toLowerCase();$('#conversation-list').innerHTML=state.conversations.filter(c=>[c.name,c.lastMessage].join(' ').toLowerCase().includes(q)).map(c=>`<button class="conversation-item ${c.id===state.selectedId?'is-active':''}" data-id="${c.id}"><strong>${c.name}</strong><span>${c.lastMessage||'Aucun message'}</span></button>`).join('');document.querySelectorAll('.conversation-item').forEach(b=>b.onclick=()=>selectConversation(Number(b.dataset.id)))}
  async function loadConversations(){const d=await api('/api/chat/conversations');state.conversations=d.conversations;renderConversations()}
  async function selectConversation(id){state.selectedId=id;renderConversations();const d=await api(`/api/chat/conversations/${id}/messages`);const conv=state.conversations.find(c=>c.id===id);$('#conversation-header').textContent=conv?.name||'Conversation';$('#message-list').innerHTML=d.messages.map(m=>`<article class="message-bubble ${m.sender.id===state.currentUser.id?'mine':''}"><strong>${m.sender.name}</strong><p>${m.body||''}</p>${m.attachmentUrl?`<a href="${m.attachmentUrl}" target="_blank">Pièce jointe</a>`:''}<small>${m.createdAt}</small></article>`).join('');$('#message-list').scrollTop=$('#message-list').scrollHeight}
  async function init(){const meta=await api('/api/chat/meta');state.currentUser=meta.currentUser;$('#conversation-department').innerHTML=meta.departments.map(d=>`<option>${d}</option>`).join('');$('#conversation-members').innerHTML='<legend>Membres</legend>'+meta.users.filter(u=>u.id!==state.currentUser.id).map(u=>`<label><input type="checkbox" value="${u.id}">${u.username} — ${u.department}</label>`).join('');await loadConversations()}
  $('#new-conversation').onclick=()=>dialog.showModal();$('#cancel-conversation').onclick=()=>dialog.close();$('#conversation-search').oninput=renderConversations;$('#conversation-form').onsubmit=async e=>{e.preventDefault();const d=await api('/api/chat/conversations',{method:'POST',body:JSON.stringify({type:$('#conversation-type').value,name:$('#conversation-name').value.trim(),department:$('#conversation-department').value,memberIds:[...document.querySelectorAll('#conversation-members input:checked')].map(x=>Number(x.value))})});dialog.close();show(d.message);await loadConversations();selectConversation(d.conversationId)};$('#message-form').onsubmit=async e=>{e.preventDefault();if(!state.selectedId)return show('Sélectionnez une conversation.');const d=await api(`/api/chat/conversations/${state.selectedId}/messages`,{method:'POST',body:JSON.stringify({body:$('#message-body').value.trim(),attachmentUrl:$('#message-attachment').value.trim()})});$('#message-body').value='';$('#message-attachment').value='';show(d.message);selectConversation(state.selectedId);loadConversations()};
  setInterval(()=>{if(state.selectedId)selectConversation(state.selectedId).catch(()=>{});loadConversations().catch(()=>{})},5000);
  init().catch(e=>show(e.message));
})();