'use strict';
(() => {
  const state={folders:[],documents:[],selectedFolder:null,selectedDocument:null,canManage:false};const $=s=>document.querySelector(s),toast=$('#toast'),fd=$('#folder-dialog'),dd=$('#document-dialog'),vd=$('#version-dialog');const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200)};async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  function renderFolders(){ $('#folder-list').innerHTML=`<button class="folder-item ${state.selectedFolder===null?'is-active':''}" data-id="">Tous les documents</button>`+state.folders.map(f=>`<button class="folder-item ${state.selectedFolder===f.id?'is-active':''}" data-id="${f.id}">${f.name}</button>`).join('');document.querySelectorAll('.folder-item').forEach(b=>b.onclick=()=>{state.selectedFolder=b.dataset.id?Number(b.dataset.id):null;renderFolders();loadDocuments()});$('#document-folder').innerHTML='<option value="">Sans dossier</option>'+state.folders.map(f=>`<option value="${f.id}">${f.name}</option>`).join('')}
  function renderDocuments(){const q=$('#document-search').value.toLowerCase();$('#document-list').innerHTML=state.documents.filter(d=>[d.title,d.summary,...d.tags].join(' ').toLowerCase().includes(q)).map(d=>`<button class="document-item ${state.selectedDocument===d.id?'is-active':''}" data-id="${d.id}"><strong>${d.title}</strong><span>v${d.currentVersion} · ${d.visibility}</span></button>`).join('')||'<p>Aucun document.</p>';document.querySelectorAll('.document-item').forEach(b=>b.onclick=()=>openDocument(Number(b.dataset.id)))}
  async function loadFolders(){const d=await api('/api/document-library/folders');state.folders=d.folders;state.canManage=d.canManage;$('#new-folder').hidden=!d.canManage;$('#new-document').hidden=!d.canManage;renderFolders()}
  async function loadDocuments(){const p=new URLSearchParams();if(state.selectedFolder)p.set('folderId',state.selectedFolder);const d=await api('/api/document-library/documents?'+p);state.documents=d.documents;renderDocuments()}
  async function openDocument(id){state.selectedDocument=id;renderDocuments();const d=await api(`/api/document-library/documents/${id}`);$('#document-placeholder').hidden=true;$('#document-content').hidden=false;$('#reader-title').textContent=d.document.title;$('#reader-meta').textContent=`${d.document.authorName} · version ${d.document.currentVersion} · ${d.document.visibility}`;$('#reader-summary').textContent=d.document.summary||'';$('#reader-body').textContent=d.versions[0]?.content||'';$('#new-version').hidden=!d.canManage;$('#version-list').innerHTML=d.versions.map(v=>`<article class="version-item"><strong>Version ${v.versionNumber}</strong><span>${v.authorName} · ${v.createdAt}</span><p>${v.changeNote||''}</p></article>`).join('');$('#version-body').value=d.versions[0]?.content||''}
  $('#document-search').oninput=renderDocuments;$('#new-folder').onclick=()=>fd.showModal();$('#new-document').onclick=()=>dd.showModal();$('#new-version').onclick=()=>vd.showModal();$('#cancel-folder').onclick=()=>fd.close();$('#cancel-document').onclick=()=>dd.close();$('#cancel-version').onclick=()=>vd.close();
  $('#folder-form').onsubmit=async e=>{e.preventDefault();const d=await api('/api/document-library/folders',{method:'POST',body:JSON.stringify({name:$('#folder-name').value.trim(),department:$('#folder-department').value.trim(),description:$('#folder-description').value.trim()})});fd.close();e.target.reset();show(d.message);loadFolders()};
  $('#document-form').onsubmit=async e=>{e.preventDefault();const d=await api('/api/document-library/documents',{method:'POST',body:JSON.stringify({folderId:$('#document-folder').value?Number($('#document-folder').value):null,title:$('#document-title').value.trim(),summary:$('#document-summary').value.trim(),tags:$('#document-tags').value.split(',').map(x=>x.trim()).filter(Boolean),visibility:$('#document-visibility').value,department:$('#document-department').value.trim(),content:$('#document-body').value.trim()})});dd.close();e.target.reset();show(d.message);loadDocuments();openDocument(d.documentId)};
  $('#version-form').onsubmit=async e=>{e.preventDefault();const d=await api(`/api/document-library/documents/${state.selectedDocument}/versions`,{method:'POST',body:JSON.stringify({content:$('#version-body').value.trim(),changeNote:$('#version-note').value.trim()})});vd.close();show(d.message);openDocument(state.selectedDocument)};
  (async()=>{await loadFolders();await loadDocuments()})().catch(e=>show(e.message));
})();