'use strict';
(() => {
  const state={employees:[],filtered:[],selectedId:null,detail:null,tab:'info'};const $=s=>document.querySelector(s),toast=$('#toast');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200)};
  async function api(url){const r=await fetch(url,{headers:{Accept:'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  function fmt(v){if(!v)return'—';return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v.endsWith?.('Z')?v:v+'Z'))}
  function renderList(){const c=$('#employee-list');c.innerHTML=state.filtered.map(e=>`<button class="employee-item ${e.id===state.selectedId?'is-selected':''}" data-id="${e.id}"><img src="${e.avatarUrl||'/assets/logos/abyss-nexus-logo.png'}"><span><strong>${esc(e.username)}</strong><small>${esc(e.matricule)} · ${esc(e.grade)} · ${esc(e.department)}</small></span></button>`).join('');document.querySelectorAll('.employee-item').forEach(b=>b.onclick=()=>select(Number(b.dataset.id)))}
  function cards(items,renderer){return items.length?items.map(renderer).join(''):'<p>Aucune donnée.</p>'}
  function renderTab(){const d=state.detail,e=d.employee;let html='';if(state.tab==='info')html=`<article class="tab-card"><strong>Identifiant</strong><p>${esc(e.identifier)}</p></article><article class="tab-card"><strong>Signature</strong><p>${esc(e.signature||'Aucune')}</p></article><article class="tab-card"><strong>Créé le</strong><p>${fmt(e.createdAt)}</p></article><article class="tab-card"><strong>Dernière connexion</strong><p>${fmt(e.lastLoginAt)}</p></article>`;if(state.tab==='reports')html=cards(d.reports,x=>`<article class="tab-card"><strong>${esc(x.report_number)} — ${esc(x.title)}</strong><p>${esc(x.status)} · ${fmt(x.created_at)}</p></article>`);if(state.tab==='sanctions')html=cards(d.sanctions,x=>`<article class="tab-card"><strong>${esc(x.sanction_number)} — ${esc(x.sanction_type)}</strong><p>${esc(x.status)} · ${fmt(x.created_at)}</p></article>`);if(state.tab==='evaluations')html=cards(d.evaluations,x=>`<article class="tab-card"><strong>${Number(x.overall_score).toFixed(2)}/5</strong><p>${esc(x.comment||'Sans commentaire')} · ${esc(x.evaluator_name||'Système')}</p></article>`);if(state.tab==='training')html=cards(d.training,x=>`<article class="tab-card"><strong>${esc(x.title)}</strong><p>${esc(x.category)} · ${esc(x.status)}</p></article>`);if(state.tab==='career')html=cards(d.career,x=>`<article class="tab-card"><strong>${esc(x.title)}</strong><p>${esc(x.event_type)} · ${fmt(x.event_date)}</p><span>${esc(x.description||'')}</span></article>`);if(state.tab==='history')html=cards(d.history,x=>`<article class="tab-card"><strong>${esc(x.action)}</strong><p>${esc(x.details||'')} · ${esc(x.actor_name||'Système')} · ${fmt(x.created_at)}</p></article>`);$('#employee-tab-content').innerHTML=html}
  async function select(id){state.selectedId=id;renderList();state.detail=await api(`/api/employees/${id}`);const e=state.detail.employee;$('#employee-placeholder').hidden=true;$('#employee-content').hidden=false;$('#employee-avatar').src=e.avatarUrl||'/assets/logos/abyss-nexus-logo.png';$('#employee-name').textContent=e.username;$('#employee-meta').textContent=`${e.matricule} · ${e.grade} · ${e.department}`;$('#employee-status').textContent=e.status;renderTab()}
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');state.tab=b.dataset.tab;renderTab()});
  $('#employee-search').oninput=e=>{const q=e.target.value.toLowerCase();state.filtered=state.employees.filter(x=>[x.username,x.matricule,x.grade,x.department].join(' ').toLowerCase().includes(q));renderList()};
  (async()=>{const d=await api('/api/employees');state.employees=d.employees;state.filtered=[...d.employees];renderList();if(state.employees[0])select(state.employees[0].id)})().catch(e=>show(e.message));
})();