'use strict';
(() => {
  const state={meta:null,campaigns:[]};const $=s=>document.querySelector(s),toast=$('#toast'),cd=$('#campaign-dialog'),td=$('#template-dialog');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200)};
  async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  function render(){const total=state.campaigns.length,sent=state.campaigns.filter(x=>x.status==='sent').length,scheduled=state.campaigns.filter(x=>x.status==='scheduled').length,rec=state.campaigns.reduce((s,x)=>s+x.recipientCount,0),read=state.campaigns.reduce((s,x)=>s+x.readCount,0);$('#campaign-total').textContent=total;$('#campaign-sent').textContent=sent;$('#campaign-scheduled').textContent=scheduled;$('#campaign-read-rate').textContent=rec?`${Math.round(read/rec*100)}%`:'0%';$('#campaign-list').innerHTML=state.campaigns.map(c=>`<article class="campaign-item campaign-priority-${c.priority}"><div><strong>${c.title}</strong><p>${c.content.slice(0,180)}</p><span class="campaign-status">${c.status}</span></div><div><span>${c.recipientCount} destinataire(s)</span><p>${c.readCount} lecture(s)</p></div><div class="campaign-actions">${c.status!=='sent'?`<button class="primary-action send-campaign" data-id="${c.id}">Envoyer</button>`:''}</div></article>`).join('')||'<p>Aucune communication.</p>';document.querySelectorAll('.send-campaign').forEach(b=>b.onclick=async()=>{const d=await api(`/api/communication-center/campaigns/${b.dataset.id}/send`,{method:'POST'});show(d.message);load()})}
  async function load(){const [meta,campaigns]=await Promise.all([api('/api/communication-center/meta'),api('/api/communication-center/campaigns')]);state.meta=meta;state.campaigns=campaigns.campaigns;$('#campaign-template').innerHTML='<option value="">Aucun modèle</option>'+meta.templates.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');$('#campaign-departments').innerHTML='<legend>Départements</legend>'+meta.departments.map(d=>`<label><input type="checkbox" value="${d}">${d}</label>`).join('');$('#campaign-users').innerHTML='<legend>Employés</legend>'+meta.users.map(u=>`<label><input type="checkbox" value="${u.id}">${u.username} — ${u.department}</label>`).join('');render()}
  function body(sendNow){return {title:$('#campaign-title').value.trim(),content:$('#campaign-content').value.trim(),priority:$('#campaign-priority').value,audienceType:$('#campaign-audience').value,departments:[...document.querySelectorAll('#campaign-departments input:checked')].map(x=>x.value),userIds:[...document.querySelectorAll('#campaign-users input:checked')].map(x=>Number(x.value)),scheduledAt:$('#campaign-scheduled-at').value?new Date($('#campaign-scheduled-at').value).toISOString():null,sendNow}}
  async function save(sendNow){const d=await api('/api/communication-center/campaigns',{method:'POST',body:JSON.stringify(body(sendNow))});cd.close();$('#campaign-form').reset();show(d.message);load()}
  $('#new-campaign').onclick=()=>cd.showModal();$('#new-template').onclick=()=>td.showModal();$('#cancel-campaign').onclick=()=>cd.close();$('#cancel-template').onclick=()=>td.close();$('#campaign-template').onchange=()=>{const t=state.meta.templates.find(x=>x.id===Number($('#campaign-template').value));if(t){$('#campaign-title').value=t.title;$('#campaign-content').value=t.content;$('#campaign-priority').value=t.priority}};$('#campaign-form').onsubmit=e=>{e.preventDefault();save(true).catch(err=>show(err.message))};$('#save-campaign-draft').onclick=()=>save(false).catch(err=>show(err.message));$('#template-form').onsubmit=async e=>{e.preventDefault();const d=await api('/api/communication-center/templates',{method:'POST',body:JSON.stringify({name:$('#template-name').value.trim(),title:$('#template-title').value.trim(),priority:$('#template-priority').value,content:$('#template-content').value.trim()})});td.close();e.target.reset();show(d.message);load()};load().catch(e=>show(e.message));
})();