'use strict';
(() => {
  const state={departments:[],filtered:[],permissions:[],selectedId:null};const $=s=>document.querySelector(s),toast=$('#toast'),dialog=$('#create-dialog');
  const show=m=>{toast.textContent=m;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2300)};
  async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',Accept:'application/json',...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok)throw new Error(d.message||'Erreur');return d}
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  function renderList(){const c=$('#department-list');c.innerHTML=state.filtered.map(d=>`<button class="department-item ${d.id===state.selectedId?'is-selected':''}" data-id="${d.id}"><span class="department-icon" style="background:${d.color}22;color:${d.color}">${esc(d.icon||'🏢')}</span><span><strong>${esc(d.name)}</strong><small>${d.active?'Actif':'Désactivé'}</small></span></button>`).join('');document.querySelectorAll('.department-item').forEach(b=>b.onclick=()=>select(Number(b.dataset.id)))}
  async function load(){const d=await api('/api/departments');state.departments=d.departments;state.filtered=[...d.departments];renderList()}
  function renderPermissions(selected){$('#department-permissions').innerHTML=state.permissions.map(p=>`<label><input type="checkbox" value="${p.key}" ${selected.includes(p.key)?'checked':''}><span>${esc(p.label)}</span></label>`).join('')}
  async function select(id){state.selectedId=id;renderList();const d=await api(`/api/departments/${id}`);$('#department-placeholder').hidden=true;$('#department-content').hidden=false;$('#department-name').value=d.department.name;$('#department-color').value=d.department.color||'#3aa9ff';$('#department-icon').value=d.department.icon||'🏢';$('#department-description').value=d.department.description||'';$('#department-active').checked=d.department.active;renderPermissions(d.permissions);$('#department-members').innerHTML=d.members.length?d.members.map(m=>`<article class="member-item"><strong>${esc(m.username)}</strong><span>${esc(m.matricule)} · ${esc(m.grade)} · ${esc(m.status)}</span></article>`).join(''):'<p>Aucun employé.</p>'}
  $('#department-search').oninput=e=>{const q=e.target.value.toLowerCase();state.filtered=state.departments.filter(d=>[d.name,d.description].join(' ').toLowerCase().includes(q));renderList()};
  $('#department-form').onsubmit=async e=>{e.preventDefault();try{const d=await api(`/api/departments/${state.selectedId}`,{method:'PUT',body:JSON.stringify({name:$('#department-name').value.trim(),color:$('#department-color').value,icon:$('#department-icon').value.trim(),description:$('#department-description').value.trim(),active:$('#department-active').checked,permissions:[...document.querySelectorAll('#department-permissions input:checked')].map(x=>x.value)})});show(d.message);await load();await select(state.selectedId)}catch(err){show(err.message)}};
  $('#delete-department').onclick=async()=>{if(!confirm('Supprimer ce département ?'))return;try{const d=await api(`/api/departments/${state.selectedId}`,{method:'DELETE'});show(d.message);state.selectedId=null;$('#department-content').hidden=true;$('#department-placeholder').hidden=false;load()}catch(err){show(err.message)}};
  $('#create-department').onclick=()=>dialog.showModal();$('#cancel-create').onclick=()=>dialog.close();
  $('#create-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/departments',{method:'POST',body:JSON.stringify({name:$('#create-name').value.trim(),color:$('#create-color').value,icon:$('#create-icon').value.trim(),description:$('#create-description').value.trim(),active:true})});dialog.close();e.target.reset();show(d.message);load()}catch(err){$('#create-message').textContent=err.message}};
  (async()=>{const m=await api('/api/departments/meta');state.permissions=m.permissions;await load();if(state.departments[0])select(state.departments[0].id)})().catch(e=>show(e.message));
})();